language: ruby
cache: bundler
rvm:
  - 2.2.2
before_install:
  - gem install bundler
before_script:
  - bundle install
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database epets_test;' -U postgres
script: bundle exec rake
