language: ruby
cache: bundler
rvm:
  - 2.2.2
before_install:
  - gem install bundler
before_script:
  - bundle install
  - psql -c 'create database epets_test;' -U postgres
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
script: bundle exec rake
after_script:
  - RAILS_ENV=test bundle exec rake sunspot:solr:stop
