development: &DEV
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

development_with_caching:
  <<: *DEV

test: &TEST
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    
cucumber:
  <<: *TEST

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
  auto_commit_after_request: false

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
  auto_commit_after_request: false
